name = "news-cms"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "news_db"
database_id = "915f7528-c3d3-43de-90e8-3cde5bac29a9"
migrations_dir = "migrations"

[vars]
SITE_URL = "https://news-cms.someshsoftwareengineer-233.workers.dev"
ENVIRONMENT = "production"

# Set secret:  npx wrangler secret put SESSION_SECRET
# SESSION_SECRET = "set-via-wrangler-secret"

[observability]
enabled = true
